"""
Table-based Shield Wrapper for CARLA (PPO-Shielding baseline).

Architecture (based on student's implementation):
  - Offline: generate shield_table.pkl via make_dummy_shield.py
  - Runtime: abstract state z -> lookup allowed_action_ids -> filter PPO action

Verified attribute paths for CarlaRouteEnv:
  env.world.world     -> CARLA World object
  env.world.map       -> CARLA Map object
  env.vehicle.actor   -> CARLA Actor object
  env.vehicle.get_speed() -> speed in km/h
  env.distance_from_center -> float (updated each step)
  env.discrete_actions -> dict {action_id: [throttle, steer]}
  env.action_space_type -> "discrete" or "continuous"

Usage:
    shield = TableShield.load_pkl("shield_table.pkl")
    env = CarlaShieldWrapper(env, shield)
"""

import pickle
from typing import List, Optional

import gym
import numpy as np
import carla

from carla_env.tools.misc import is_within_distance_ahead


class TableShield:
    """
    Maps abstract state z -> list of allowed action IDs.
    Load from a .pkl file generated by make_dummy_shield.py.
    Returns None for unknown states (= no intervention).
    """
    def __init__(self, table: dict):
        self.table = table  # dict[tuple] -> list[int]

    @classmethod
    def load_pkl(cls, path: str) -> "TableShield":
        with open(path, "rb") as f:
            table = pickle.load(f)
        return cls(table)

    def allowed_actions(self, z) -> Optional[List[int]]:
        return self.table.get(z, None)


class CarlaShieldWrapper(gym.Wrapper):
    """
    Wraps CarlaRouteEnv with runtime action filtering:
      1. Compute abstract state z from env state
      2. Look up allowed actions from shield table
      3. If PPO action is not safe, replace with nearest safe action
      4. Log intervention stats in info dict

    Requires: env.action_space_type == "discrete"
    """

    def __init__(
        self,
        env: gym.Env,
        shield: TableShield,
        max_front_dist: float = 50.0,
        tl_check_dist: float = 12.0,
    ):
        super().__init__(env)
        self.shield = shield
        self.max_front_dist = max_front_dist
        self.tl_check_dist = tl_check_dist

        assert hasattr(env, "action_space_type"), \
            "env must have action_space_type (should be CarlaRouteEnv)"
        assert hasattr(env, "discrete_actions"), \
            "env must have discrete_actions dict (add self.discrete_actions = discrete_actions in CarlaRouteEnv.__init__)"

    # ------------------------------------------------------------------
    # State abstraction
    # ------------------------------------------------------------------

    def _get_red_light_flag(self) -> bool:
        """Check if there is a red traffic light ahead of the ego vehicle."""
        world = self.env.world.world
        ego_actor = self.env.vehicle.actor
        amap = self.env.world.map

        ego_loc = ego_actor.get_location()
        ego_wp = amap.get_waypoint(ego_loc)

        for tl in world.get_actors().filter("*traffic_light*"):
            tl_wp = amap.get_waypoint(tl.get_location())
            if tl_wp.road_id != ego_wp.road_id or tl_wp.lane_id != ego_wp.lane_id:
                continue
            if is_within_distance_ahead(
                tl.get_location(), ego_loc,
                ego_actor.get_transform().rotation.yaw,
                self.tl_check_dist,
            ):
                return tl.state == carla.TrafficLightState.Red
        return False

    def _get_front_dist(self) -> float:
        """Distance to the nearest vehicle directly ahead in the same lane."""
        world = self.env.world.world
        ego_actor = self.env.vehicle.actor
        amap = self.env.world.map

        ego_tf = ego_actor.get_transform()
        ego_loc = ego_tf.location
        ego_wp = amap.get_waypoint(ego_loc)

        min_d = self.max_front_dist
        for v in world.get_actors().filter("vehicle.*"):
            if v.id == ego_actor.id:
                continue
            v_wp = amap.get_waypoint(v.get_location())
            if v_wp.road_id != ego_wp.road_id or v_wp.lane_id != ego_wp.lane_id:
                continue
            if is_within_distance_ahead(
                v.get_location(), ego_loc, ego_tf.rotation.yaw, self.max_front_dist
            ):
                d = ego_loc.distance(v.get_location())
                if d < min_d:
                    min_d = d
        return float(min_d)

    def _abstract_state(self):
        """
        Abstract continuous state into a hashable tuple z.
        z = (lane_bin, speed_bin, red_bin, front_bin)

        lane_bin : 0=good(<0.7m), 1=warn(<1.5m), 2=bad(>=1.5m)
        speed_bin: 0=slow(<10), 1=mid(<25), 2=fast(>=25)  [km/h]
        red_bin  : 0=green,     1=red
        front_bin: 0=close(<6m),1=near(<12m), 2=far(>=12m)
        """
        d_center = float(getattr(self.env, "distance_from_center", 0.0))
        v_kmh = float(self.env.vehicle.get_speed())
        red = self._get_red_light_flag()
        front_d = self._get_front_dist()

        lane_bin = 0 if d_center < 0.7 else (1 if d_center < 1.5 else 2)
        speed_bin = 0 if v_kmh < 10 else (1 if v_kmh < 25 else 2)
        front_bin = 0 if front_d < 6 else (1 if front_d < 12 else 2)
        red_bin = 1 if red else 0

        return (lane_bin, speed_bin, red_bin, front_bin)

    # ------------------------------------------------------------------
    # Action selection
    # ------------------------------------------------------------------

    def _pick_safe_action(self, a_id: int, safe_ids: List[int]) -> int:
        """
        If a_id is already safe, return it.
        Otherwise pick the safe action with smallest L2 distance in
        [throttle, steer] space.
        """
        if a_id in safe_ids:
            return a_id

        target = np.array(self.env.discrete_actions[a_id], dtype=np.float32)

        best, best_dist = None, 1e9
        for sid in safe_ids:
            cand = np.array(self.env.discrete_actions[sid], dtype=np.float32)
            d = float(np.linalg.norm(cand - target))
            if d < best_dist:
                best_dist = d
                best = sid
        return int(best) if best is not None else int(np.random.choice(safe_ids))

    # ------------------------------------------------------------------
    # Gym interface
    # ------------------------------------------------------------------

    def step(self, action):
        intervened = 0.0

        if self.env.action_space_type == "discrete":
            z = self._abstract_state()
            safe_ids = self.shield.allowed_actions(z)

            if safe_ids is not None and len(safe_ids) > 0:
                a_id = int(action)
                new_id = self._pick_safe_action(a_id, safe_ids)
                if new_id != a_id:
                    intervened = 1.0
                    action = new_id
        # For continuous action spaces: no intervention (shield table is discrete-only)

        out = self.env.step(action)
        # Support both old gym (4-tuple) and new gymnasium (5-tuple)
        if len(out) == 5:
            obs, reward, terminated, truncated, info = out
        else:
            obs, reward, done, info = out
            terminated, truncated = bool(done), False

        info["shield_intervened"] = float(intervened)

        if len(out) == 5:
            return obs, reward, terminated, truncated, info
        else:
            return obs, reward, bool(terminated or truncated), info
